### ISSUE TITLE
[BUG] Chat API 오류 핸들링

### ISSUE THREAD

**Issue by hyunmin0317** [hyunmin0317/spring-boot-gpt#5]
## 문제 상황

- Chat API 의 모든 오류가 `ACCOUNT007` 로 나옴
  ```json
  {
    "code": "ACCOUNT007",
    "message": "로그인 후 이용가능합니다. 토큰을 입력해 주세요."
  }
  ```

## 서버 로그
```
org.springframework.web.HttpMediaTypeNotAcceptableException: No acceptable representation
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:256) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:245) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78) ~[spring-web-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:136) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException(ExceptionHandlerExceptionResolver.java:432) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver.doResolveException(AbstractHandlerMethodExceptionResolver.java:74) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.resolveException(AbstractHandlerExceptionResolver.java:175) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.handler.HandlerExceptionResolverComposite.resolveException(HandlerExceptionResolverComposite.java:80) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1357) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1160) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1106) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
```

**Comment by hyunmin0317** [comment]
## 문제 원인

- `accept: text/event-stream` 헤더의 Request 의 경우
- `JwtAuthenticationFilter` 에서 오류 발생

## 해결과정

- `JwtAuthenticationFilter` 가 `text/event-stream` 타입의 Request 를 처리하지 못함
- `text/event-stream` 에 대한 Filter 예외처리 추가

**Comment by hyunmin0317** [comment]
## `accept` 헤더에 따라 다름

- 오류 핸들링 X
  - `accept: text/event-stream`
  - Curl
    ```Curl
    curl -X 'POST' \
      'http://localhost:8080/api/v1/chat' \
      -H 'accept: text/event-stream' \
      -H 'Content-Type: application/json' \
      -d '{
      "prompt": ""
    }'
    ``` 
  - Response Body
    ```json
    {
      "code": "ACCOUNT007",
      "message": "로그인 후 이용가능합니다. 토큰을 입력해 주세요."
    }
    ```
- 오류 핸들링 O
  - `accept: */*`
  - Curl
    ```Curl
    curl -X 'POST' \
      'http://localhost:8080/api/v1/chat' \
      -H 'accept: */*' \
      -H 'Content-Type: application/json' \
      -d '{
      "prompt": ""
    }'
    ``` 
  - Response Body
    ```json
    {
      "code": "VALID001",
      "message": "입력값에 대한 검증에 실패했습니다.",
      "detail": {
        "prompt": "프롬프트를 입력해주세요."
      }
    }
    ```

**Comment by hyunmin0317** [comment]
## 오류원인
- `accept` 헤더가 `text/event-stream` 일 경우 (Swagger) -> OncePerRequestFilter 에서 오류 발생 -> 인증 오류 (authenticationEntryPoint)
- 클라이언트에서 `accept` 헤더 `*/*` 로 설정 필요 (Postman, Client)
- Swagger 에서 `@PostMapping(produces = MediaType.TEXT_EVENT_STREAM_VALUE)` 으로 인해 헤더가 `accept: text/event-stream` 으로 설정됨
- Swagger 설정 변경 필요
- 헤더 설정 문제로 코드 문제 X -> 이슈 종료
